/*
 * JSP generated by Resin-3.0.21 (built Thu, 10 Aug 2006 12:03:19 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import dao.*;
import util.*;
import java.util.*;
import org.apache.commons.lang.StringUtils;
import vo.*;

public class _edit_0time_0info_0iframe__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
  
  	TimeInfoDAO dao =TimeInfoDAO.getInstance();
  	
  	Map<String,Object> whereMap =new HashMap<String,Object>();
  	System.out.println(request.getRequestURL());
 	long id =Long.parseLong(request.getParameter("id"));
 	whereMap.put("id",id);
 	
 	
 	
 	Map<String,Object> map =dao.getOne(whereMap);
  
      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((id ));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((map.get("title") ));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((map.get("start_time") ));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((map.get("end_time") ));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      if(map.get("type").equals("\u5de5\u4f5c")){ out.print("selected =\"selected\"" ); }
      out.write(_jsp_string6, 0, _jsp_string6.length);
      if(map.get("type").equals("\u5b66\u4e60")){ out.print("selected =\"selected\"" ); }
      out.write(_jsp_string7, 0, _jsp_string7.length);
      if(map.get("type").equals("\u5a31\u4e50")){ out.print("selected =\"selected\"" ); }
      out.write(_jsp_string8, 0, _jsp_string8.length);
      if(map.get("type").equals("\u8d2d\u7269")){ out.print("selected =\"selected\"" ); }
      out.write(_jsp_string9, 0, _jsp_string9.length);
      if(map.get("type").equals("\u4ee3\u7801")){ out.print("selected =\"selected\"" ); }
      out.write(_jsp_string10, 0, _jsp_string10.length);
      if(map.get("type").equals("\u5fc5\u987b\u65f6\u95f4")){ out.print("selected =\"selected\"" ); }
      out.write(_jsp_string11, 0, _jsp_string11.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -6418134904411496499L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("edit_time_info_iframe.jsp"), -2529525047542515637L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string7;
  private final static char []_jsp_string9;
  private final static char []_jsp_string8;
  private final static char []_jsp_string2;
  private final static char []_jsp_string1;
  private final static char []_jsp_string4;
  private final static char []_jsp_string11;
  private final static char []_jsp_string6;
  private final static char []_jsp_string10;
  private final static char []_jsp_string0;
  private final static char []_jsp_string5;
  private final static char []_jsp_string3;
  static {
    _jsp_string7 = ">\u5b66\u4e60</option>\r\n		 			<option value=\"\u5a31\u4e50\" ".toCharArray();
    _jsp_string9 = ">\u8d2d\u7269</option>\r\n		 			<option value=\"\u4ee3\u7801\" ".toCharArray();
    _jsp_string8 = ">\u5a31\u4e50</option>\r\n		 			<option value=\"\u8d2d\u7269\" ".toCharArray();
    _jsp_string2 = "\"></input>\r\n		<input type=\"hidden\"  id=\"op_type\"  name=\"op_type\" value=\"edit\"></input>\r\n		 <table>\r\n		 	<tr>\r\n		 		<td> \u6807\u9898:</td>\r\n		 		<td><input type=\"text\" name=\"title\" id =\"title\"  value=\"".toCharArray();
    _jsp_string1 = "	\r\n\r\n\r\n\r\n\r\n\r\n	<form action=\"oper_time_info.jsp\" name=\"edit_form\" id=\"edit_form\" method=\"post\">\r\n	\r\n		<input type=\"hidden\"  id=\"id\" name=\"id\" value=\"".toCharArray();
    _jsp_string4 = "\"/></td>\r\n		 	</tr>\r\n			<tr>\r\n		 		<td> \u7ed3\u675f\u65f6\u95f4\uff1a</td>\r\n		 		<td><input type=\"text\" name=\"end_time\" id =\"end_time\" value=\"".toCharArray();
    _jsp_string11 = ">\u5fc5\u987b\u65f6\u95f4</option>\r\n		 		</select>\r\n		 		\r\n		 	</tr>\r\n			\r\n		 	<tr>\r\n		 	\r\n		 		<td><input type=\"submit\" value=\"\u63d0\u4ea4\" ></td>\r\n		 		<td><input type=\"button\" id=\"cancelButton\" onclick=\"self.parent.tb_remove();\" value=\"\u3000\u53d6\u3000\u6d88\u3000\"/></td>\r\n		 	</tr>\r\n 	\r\n       </table>\r\n	</form>\r\n\r\n \r\n \r\n \r\n \r\n</body>\r\n</html>".toCharArray();
    _jsp_string6 = " >\u5de5\u4f5c</option>\r\n		 			<option value=\"\u5b66\u4e60\" ".toCharArray();
    _jsp_string10 = ">\u4ee3\u7801</option>\r\n		 			<option value=\"\u5fc5\u987b\u65f6\u95f4\" ".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<html>\r\n<head>\r\n<title>\u65f6\u95f4\u8bb0\u5f55</title>\r\n</head>\r\n<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n<script type=\"text/javascript\" src=\"js/DateUtil.js\"></script>\r\n<script type=\"text/javascript\" src=\"js/thickbox.js\"></script>\r\n<link rel=\"stylesheet\" href=\"css/thickbox.css\" type=\"text/css\" media=\"screen\" />\r\n<body>\r\n\r\n\r\n  ".toCharArray();
    _jsp_string5 = "\"/></td>\r\n		 	</tr>\r\n		 	\r\n		 	<tr>\r\n		 		<td> \u7c7b\u578b:</td>\r\n		 		<td>\r\n		 		<select name=\"type\" id =\"type\">\r\n		 			<option value=\"\u5de5\u4f5c\" ".toCharArray();
    _jsp_string3 = "\"/></td>\r\n		 	</tr>\r\n		 	<tr>\r\n		 		<td> \u5f00\u59cb\u65f6\u95f4\uff1a</td>\r\n		 		<td><input type=\"text\" name=\"start_time\" id =\"start_time\" value=\"".toCharArray();
  }
}
