/*
 * JSP generated by Resin-3.0.21 (built Thu, 10 Aug 2006 12:03:19 PDT)
 */

package _jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import org.apache.commons.lang.StringUtils;
import java.util.*;
import dao.*;
import vo.*;
import util.*;

public class _oper_0time_0info__jsp extends com.caucho.jsp.JavaPage{
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.server.webapp.Application _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, null, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
TimeInfoDAO  dao =TimeInfoDAO.getInstance();
String op_type =request.getParameter("op_type");
if("post".equalsIgnoreCase(request.getMethod()))
{
	
	String title =request.getParameter("title");
	String content =request.getParameter("content");
	String type =request.getParameter("type");
	
    String start_time =request.getParameter("start_time");
    String end_time =request.getParameter("end_time");
   if("add".equalsIgnoreCase(op_type))
   {
	    Map<String,Object> map =new HashMap<String,Object>();
		
		map.put("id",System.currentTimeMillis());
		map.put("start_time",start_time);
		if(StringUtils.isNotEmpty(end_time))
		{
			map.put("end_time",end_time);
		}
		map.put("title",title);
		map.put("type",type);
		map.put("add_time",DateUtil.getCurrent());
		

		if(dao.insert(map))
		{
			out.println(JspUtil.getJs("\u6dfb\u52a0\u6210\u529f",true,""));
			return ;
		}
		else{
			out.println(JspUtil.getJs("\u6dfb\u52a0\u5931\u8d25",true,""));
			return ;
		}
   }
   if("edit".equalsIgnoreCase(op_type))
   {
	   Long id =Long.parseLong(request.getParameter("id"));
		Map<String,Object> whereMap =new HashMap<String,Object>();
		whereMap.put("id",id);
		
		
	    Map<String,Object> setMap =new HashMap<String,Object>();
		
		
	    setMap.put("start_time",start_time);
		if(StringUtils.isNotEmpty(end_time))
		{
			setMap.put("end_time",end_time);
		}
		setMap.put("title",title);
		setMap.put("type",type);
		setMap.put("add_time",DateUtil.getCurrent());
		

		if(dao.edit(whereMap,setMap))
		{
			out.println(JspUtil.getJs("\u4fee\u6539\u6210\u529f",true,""));
			return ;
		}
		else{
			out.println(JspUtil.getJs("\u4fee\u6539\u5931\u8d25",true,""));
			return ;
		}
   }
}
else
{
	
	Long id =Long.parseLong(request.getParameter("id"));
	
	if("finish".equalsIgnoreCase(op_type))
	{
		Map<String,Object> whereMap =new HashMap<String,Object>();
		Map<String,Object> setMap =new HashMap<String,Object>();
		whereMap.put("id",id);
		
		setMap.put("end_time",DateUtil.getCurrent());
		
		
		if(dao.edit(whereMap,setMap))
		{
			out.println(JspUtil.getJs("\u4fee\u6539\u6210\u529f",true,""));
			return ;
		}
		else{
			out.println(JspUtil.getJs("\u4fee\u6539\u5931\u8d25",true,""));
			return ;
		}
	}

}

    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.make.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.util.CauchoSystem.getVersionId() != -6418134904411496499L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.make.Dependency depend;
      depend = (com.caucho.make.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("oper_time_info.jsp"), 8884614989496565783L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n".toCharArray();
  }
}
